version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    env_file:
        - .env_example
    expose:
      - '${FLASK_PORT}'
    depends_on:
      - db
      
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
        - .env_example
    expose:
        - 5432


  nginx:
    build: ./nginx
    container_name: nginx
    env_file:
      - .env_example
    ports:
      - "80:80"
    depends_on:
      - flask