version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    env_file:
        - .env_example
    expose:
      - 8080
    depends_on:


  nginx:
    build: ./nginx
    container_name: nginx
    env_file:
      - .env_example
    ports:
      - "80:80"
    depends_on:
      - flask